routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/app', 'Front\FrontController@app');
Route::get('/', 'Front\FrontController@home');

Route::post('/produktii', 'Front\ProduktiController@image_store')->name('image_store');
Route::delete('/produktii_delete/{post}', 'Front\ProduktiController@image_delete')->name('image_delete');

//produkti
Route::resource('produkti', 'Front\ProduktiController');
Route::get('/', 'Front\FrontController@home');

//kontakt
Route::get('/kontakt', 'Front\FrontController@kontakt');
Route::post('/mail', 'Front\FrontController@mail')->name('mail');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = 'post';

    public function produkti()
    {
        return $this->belongsTo('App\Produkti');
    }
}

app/Produkti.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produkti extends Model
{
    protected $table = 'produkti';

    public function images(){
        return $this->hasMany('App\Post');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Front/FrontController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Mail\ContactMail;
use App\Produkti;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class FrontController extends Controller
{
    public function app(){
        return view('front-end.app');
    }

    public function home(){

        $produkti=Produkti::all();
        $bla=Produkti::all();
        return view('front-end.home',compact('produkti','bla'));
    }

    public function kontakt(){
        return view('front-end.kontakt.index');
    }

    public function mail(Request $request){
        Mail::to('petargigant@live.com')->send(new ContactMail($request));
        return redirect()->back();
    }
}

app/Http/Controllers/Front/ProduktiController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Post;
use App\Produkti;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;

class ProduktiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    public function index()
    {
        $produkti = Produkti::all();
        return view('front-end.produkti.index', compact('produkti'));
    }

    public function create()
    {
        $produkti = Produkti::all();
        return view('front-end.produkti.create',compact('produkti'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
            'image' => 'image|mimes:jpg,png,jpeg,gif',
        ],
            [
                'title.required' => 'Немате внесено име',
                'description.required' => 'Немате внесено опис',
                'image.required' => 'Немате внесено слика'
            ]);

        $image = $request->file('image');

        $slug = Str::slug($request->name);

        if (isset($image)) {
            $imagename = $slug . '.' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!file_exists('uploads/produkti')) {
                mkdir('uploads/produkti', 0777, true);
            }
            $image->move('uploads/produkti', $imagename);
        } else {
            $imagename = 'default.png';
        }


        $produkti = new Produkti();
        $produkti->name = $request->name;
        $produkti->description = $request->description;
        $produkti->image = $imagename;
        $produkti->slug = $slug;

        $produkti->save();

        Session::flash('success', 'Успешно внесување');
        return redirect()->back();
    }

    public function show($slug)
    {
        $produkti = Produkti::where('slug', '=', $slug)->first();
        $image=Post::where('product_id','=',$produkti->id)->get();

        return view('front-end.produkti.show', compact('produkti','image'));
    }

    public function edit($id)
    {
        $produkti = Produkti::findorfail($id);

        return view('front-end.produkti.edit', compact('produkti'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
        ],
            [
                'title.required' => 'Немате внесено име',
                'description.required' => 'Немате внесено опис',
            ]);

        $produkti = Produkti::findorfail($id);
        $slug = Str::slug($request->name);

        $image = $request->file('image');
        if (isset($image)) {
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . '-' . uniqid() . '-' . $image->getClientOriginalName();

            if (!file_exists('uploads/produkti')) {
                mkdir('uploads/produkti', 0777, true);
            }
            $image->move('uploads/produkti', $imageName);
        } else {
            $imageName = $produkti->image;//Ako ne klaj nova slika Zemija starata
        }
        $produkti->name = $request->name;
        $produkti->description = $request->description;
        $produkti->image = $imageName;
        $produkti->slug = $slug;
        $produkti->save();

        Session::flash('success', 'Успешна Промена');
        return redirect()->back();
    }

    public function destroy($id)
    {
        $produkti = Produkti::findorfail($id);
        if (file_exists('uploads/produkti/' . $produkti->image)) {
            unlink('uploads/produkti/' . $produkti->image);
        }
        $produkti->delete();
        return redirect()->route('produkti.index');
    }

    public function image_store(Request $request)
    {
        foreach (request()->file('image') as $file) {
            $imagealbum = new Post();
            $filename = $file->getClientOriginalName();

            if (!file_exists('uploads/post')) {
                mkdir('uploads/post', 0777, true);
            }
            $file->move('uploads/post', $filename);
            $imagealbum->product_id = $request->post;
            $imagealbum->image = $filename;

            $imagealbum->save();
        }
        return redirect()->route('produkti.index');
    }

    public function image_delete($id){
        $imagealbum=Post::findorfail($id);
        if (file_exists('uploads/post/' . $imagealbum->image)) {
            unlink('uploads/post/' . $imagealbum->image);
        }
        $imagealbum->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/front-end/app.blade.php
<!DOCTYPE html>
<!--[if IE 8 ]>
<html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->

<head>
    <!-- Basic Page Needs
================================================== -->
    <meta charset="utf-8">
    <title>Mrse2007</title>
    <!-- Favicon
    ============================================== -->
    <!-- Mobile Specific
=================================================composer= -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- CSS Files
================================================== -->
@include('front-end.layouts.header')

<!-- Modernizr js file
================================================== -->
    <script src="{{asset('front-end/js/modernizr.custom.js')}}"></script>
</head>

<body>
<!-- loader -->
<div class="loader">
    <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
    </div>
</div>
<!-- /loader -->
<!-- content wrapper -->
<div class="content-wrap">

    <div class="content">

    @include('front-end.layouts.top-bar')

    @include('front-end.layouts.navigation')

    @include('front-end.layouts.msg')

    @yield('content')


        @include('front-end.layouts.footer')
<!--/content wrapper -->

<!-- JS Files
================================================== -->
@include('front-end.layouts.scripts')

</body>

</html>

resources/views/front-end/home.blade.php
@extends('front-end.app')

@section('content')
    @include('front-end.layouts.slider')
    <!-- /.fullwidthbanner-container -->


    <!-- services section -->
    <section class="bg-white">

        <div class="row">
            <div class="col-md-4 box-dark color1" style="height: 280px">
                <div class="services-box-3">
                    <i class="icon-picons-configuration"></i>
                    <div class="content">
                        <h3>Кратка биографија</h3>
                        <p>Мрсе 2007 е фамилијарно основана фирма во Прилеп. </p>
                    </div>
                </div>
            </div>

            <div class="col-md-4 box-dark" style="height: 280px">
                <div class="services-box-3">
                    <i class="icon-picons-ruler"></i>
                    <div class="content">

                        <h3>Производи</h3>
                        <p>Изработуваме алуминиумски и ковани огради и порти, метални настрешници,
                            челични конструции, изработка на панели на CNC и изработка на интериер од метал.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4 box-dark color2" style="height: 280px">
                <div class="services-box-3">
                    <i class="icon-picons-pencil-ruler"></i>
                    <div class="content">
                        <h3>Проширеност</h3>
                        <p>Изведуваме, доставуваме и монтираме низ цела Македонија.</p>
                    </div>
                </div>
            </div>

        </div>

    </section>
    <!--/ services section -->


    <!-- features section -->
    <section>

        <div class="container pad-container2">

            <div class="row">

                <div class="col-md-4">
                    <div class="services-box-2">
                        <i class="icon-picons-plane"></i>
                        <div class="content">
                            <h3>Алуминиумски огради</h3>
                            <p>Се изработуваат од високо квалитетни, елуксираниалуминиумски профили и акцесоари.</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="services-box-2">
                        <i class="icon-picons-building"></i>
                        <div class="content">
                            <h3>Метални огради и порти</h3>
                            <p>Изработка на сите видови на метални огради и порти : ковани, ролента, тараба и огради и
                                порти по желба на купувачот.</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="services-box-2">
                        <i class="icon-picons-flower"></i>
                        <div class="content">
                            <h3>Настрешници</h3>
                            <p>Изработка на сите видови настрешници со лексан, лим, панел и комбнација алуминиум и метал.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row t-mgr50">

                <div class="col-md-4">
                    <div class="services-box-2">
                        <i class="icon-picons-configuration-2"></i>
                        <div class="content">
                            <h3>Челични конструкции</h3>
                            <p>Изработка и монтажа на челични конструкции од најмала гаража до производствена хала.</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="services-box-2">
                        <i class="icon-picons-hammer"></i>
                        <div class="content">
                            <h3>ЦНЦ </h3>
                            <p>Изработка на метални панели со најразлични фигури и фомри со дебелина на лим од 2-35мм.</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="services-box-2">
                        <i class="icon-picons-hammer"></i>
                        <div class="content">
                            <h3>Други услуги </h3>
                            <p>Изнајмуваме електрична платформа (подвижно скеле),изработка на интерирер од метал и
                                секакви метални продукти и продажба на аксесоари за алуминиумски огради и оков за PVC дограма. </p>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </section>
    <!-- features section -->


  @include('front-end.layouts.kategorii_list')


@include('front-end.layouts.pozadina')

    <!--/ parallax section -->


    @include('front-end.layouts.contact_bar')

@endsection

resources/views/front-end/layouts/contact_bar.blade.php
<!-- tagline section -->
<section class="bot-subscribe">
    <div class="container">

        <div class="row">

            <div class="col-sm-8">
                <p>Имате прашање?</p>
                <h3 class="color-white">Контактирајте не преку контакт формата</h3>

            </div>

            <div>
                <a class="btn btn-white" href="#" >Контакт </a>
            </div>

        </div>

    </div>

</section>
<!--/ tagline section -->

resources/views/front-end/layouts/footer.blade.php
<!-- footer -->
<footer class="footer">
    <div class="container pad-container">

        <div class="row">
            <div class="col-sm-4 ">
                <div class="widget r-pad50">
                    <a href="{{url('/login')}}"><img src="{{asset('front-end/images/logo/mrsefooter.jpg')}}" style="width: 250px" alt=""/></a>
                    <p>Мрсе 2007 е фамилијарно основана фирма во Прилеп.</p>
                    <div class="clearfix"></div>
                    <div class="social-icons text-center">
                        <ul>

                            <li><a href="#" class="facebook-alt text-center" title="Facebook" data-rel="tooltip"
                                   data-placement="top"><i class="icon-facebook"></i></a>
                            </li>
                            <li><a href="#" class="google-alt" title="Google Plus" data-rel="tooltip"
                                   data-placement="top"><i class="icon-gplus"></i></a>
                            </li>


                        </ul>
                    </div>

                </div>
            </div>
            <div class="col-sm-4">
                <div class="widget">
                    <h4>Продукти</h4>

                    <div class="col-sm-6 col-xs-12">
                        <ul class="circled">
                            @{{--foreach($bla as $blaa)
                            <li>  <a href="/produkti/{{$blaa->slug}}">{{$blaa->name}}</a></li>
                            @endforeach--}}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 ">
                <div class="widget">
                    <h4>Контакт</h4>
                    <div class="contact">
                        <i class="icon-picons-pin-2"></i>
                        <div class="content">
                            <p class="bold  t-pad30">улица "3 Ноември" број 12, <br>Прилеп, 7500
                            </p>
                        </div>
                    </div>
                    <div class="contact">
                        <i class="icon-picons-telephone-call"></i>
                        <div class="content">
                            <p class="bold  t-pad30">+389 71230015</p>
                            <p class="bold "><a href="#">Mrse_toni@hotmail.com</a></p>
                        </div>
                    </div>
                    <div class="contact">
                        <i class="icon-picons-building"></i>
                        <div class="content">
                            <p class="bold  t-pad30">Понеделник - Сабота: <br> 08:00 - 16:00
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</footer>

resources/views/front-end/layouts/msg.blade.php
@if(Session::has('success'))

    <div class="alert alert-success" role="alert">
        <strong>{{Session::get('success')}}</strong>
    </div>
@endif

@if(count($errors)>0)
    <div class="alert alert-danger" role="alert">
        <strong>Error:</strong>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>

            @endforeach
        </ul>
    </div>
@endif

resources/views/front-end/produkti/create.blade.php
@extends('front-end.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1>Креирај Нов Продукт</h1>
                <hr>
                <form method="POST" enctype="multipart/form-data" action="{{ route('produkti.store') }}">
                    @csrf

                    <div class="form-group">
                        <label name="title">Наслов:</label>
                        <input id="title" type="text" name="name"
                               class="form-control{{$errors->has('name') ? 'is-invalid' : ''}}"
                               value="{{ old('name') }}"
                               autocomplete="name" autofocus required>
                        @if($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('name') }}</strong>
                            </span>

                        @endif
                    </div>

                    <div class="form-group">
                        <label name="title">Дополнителни инфромации:</label>
                        <textarea id="description" type="text" name="description"
                                  class="form-control{{$errors->has('description') ? 'is-invalid' : ''}}"
                                  value="{{ old('description') }}"
                                  autocomplete="description" autofocus required> </textarea>
                        @if($errors->has('description'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('description') }}</strong>
                            </span>

                        @endif
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <label for="image" class="col-md-4 col-form-label">Слика:</label>
                            <input type="file" class="form-control-file" id="image" name="image" required>
                            @if($errors->has('image'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('image') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>
                    <br>
                    <input type="submit" value="Креирај Категорија" class="btn btn-success btn-lg btn-block">
                    <br>
                    <br>
                    <br>
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1>Креирај Слики за Продукт</h1>
                <hr>
                <form method="POST" action="{{route('image_store')}}" enctype="multipart/form-data">
                    @csrf

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Пост:</label>
                                <select class="form-control " name="post">
                                    <option disabled selected>Одбери</option>
                                    @foreach($produkti as $produktis)
                                        <option value="{{$produktis->id}}">{{$produktis->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <label for="image" class="col-md-4 col-form-label">Слики:</label>
                            <input type="file" class="form-control-file" id="image" name="image[]" multiple>
                            @if($errors->has('image'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('image') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>
<br>

                    <input type="submit" value="Креирај Слики" class="btn btn-success btn-lg btn-block">

                </form>

            </div>
        </div>
    </div>




@endsection

resources/views/front-end/produkti/edit.blade.php
@extends('front-end.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1>Промена на Категорија</h1>
                <hr>
                <form method="POST" enctype="multipart/form-data" action="{{ route('produkti.update',$produkti->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label name="title">Наслов:</label>
                        <input id="title" type="text" name="name"
                               class="form-control{{$errors->has('name') ? 'is-invalid' : ''}}"
                               value="{{ $produkti->name }}"
                               autocomplete="name" autofocus required>
                        @if($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('name') }}</strong>
                            </span>

                        @endif
                    </div>

                    <div class="form-group">
                        <label name="title">Дополнителни инфромации:</label>
                        <textarea id="description" type="text" name="description"
                                  class="form-control{{$errors->has('description') ? 'is-invalid' : ''}}"
                                  value="{{ old('description') }}"
                                  autocomplete="description" autofocus required>{{$produkti->description}} </textarea>
                        @if($errors->has('description'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('description') }}</strong>
                            </span>

                        @endif
                    </div>

                    <div class="row">
                        <label for="image" class="col-md-4 col-form-label" >Слика:</label>
                        <input type="file" class="form-control-file" id="image" name="image" >
                        @if($errors->has('image'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('image') }}</strong>
                            </span>
                        @endif
                    </div>

                    <input type="submit" value="Промени Категорија" class="btn btn-success btn-lg btn-block">
                    <br>
                    <br>
                    <br>
                </form>
            </div>
        </div>
    </div>


@endsection

resources/views/front-end/produkti/show.blade.php
@extends('front-end.app')

@section('content')
    <!-- inner banner -->
    <section class="bg-white inner-banner " style="background: url({{asset('uploads/produkti/'.$produkti->image)}})">

        <div class="container pad-container">
            <div class="col-md-12">
                <h1>Project Details</h1>
                <h3>Showcasing what we do</h3>
            </div>
        </div>

    </section>
    <!-- / inner banner -->
    <!-- skills section -->
    <section class="bg-gray">

        <div class="container container-pad">

            <div class="col-sm-12">
                <h2>{{$produkti->name}}</h2>
                <p>{{$produkti->description}} </p>

            </div>
        </div>

    </section>
    <!--/ skills section -->
    <section>

        <div class="container pad-container2">
            <!-- projects grid -->
            <ul class="projects-grid-3 project-grid-gut hide-titles" id="project-grid">
            @foreach($image as $images)
                <!-- project Item -->
                    <li class="project-item mix branding">
                        <a href="{{asset('uploads/post/'.$images->image)}}" class="fancybox" data-rel="portfolio"
                           data-title-id="img-02">
                            <div class="project-img">
                                <img class="project-img" src="{{asset('uploads/post/'.$images->image)}}" alt="project"
                                     style="min-height: 200px;max-height:201px;"/>
                            </div>
                            @auth
                                <div class="project-intro">
                                    <div class="col-sm-12">
                                        <form
                                            id="delete-form-{{$images->id}}"
                                            action="{{route('image_delete',$images->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <button type="button" class="btn btn-danger btn-sm col-sm-6"
                                                onclick="if(confirm('Дали си Сигурен'))
                                                    {
                                                    event.preventDefault();
                                                    document.getElementById('delete-form-{{$images->id}}').submit();
                                                    }
                                                    ">
                                            Избриши
                                        </button>
                                    </div>
                                </div>
                        </a>
                        @endauth
                    </li>
                    <!-- End project Item -->
                @endforeach
            </ul>
            <!-- / projects grid -->
            <div class="col-md-12">
                <div class="col-md-5 ">
                    <div class="well col-md-5-offset-5">
                        <dl class="dl-horizontal">

                            <dt>Креирано на:</dt>
                            <dd>{{date('M j, Y H:i',strtotime($produkti->created_at))}}</dd>
                        </dl>

                        <dl class="dl-horizontal">
                            <dt>Последна промена на:</dt>
                            <dd>{{date('M j, Y H:i',strtotime($produkti->updated_at))}}</dd>
                        </dl>
                        <hr>

                        <div class="row">

                            <div class="col-sm-12">
                                <form
                                    id="delete-form-{{$produkti->id}}"
                                    action="{{route('produkti.destroy',$produkti->id)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                </form>
                                <button type="button" class="btn btn-danger btn-sm col-sm-6"
                                        onclick="if(confirm('Дали си Сигурен'))
                                            {
                                            event.preventDefault();
                                            document.getElementById('delete-form-{{$produkti->id}}').submit();
                                            }
                                            ">
                                    Избриши
                                </button>
                                <div class="col-sm-6">
                                    <a class="btn btn-danger btn-sm col-sm-12" href="{{route("produkti.create")}}"
                                    >Додај Слики </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </section>
    <!--/ portfolio section -->
    <section>
        <aside>

        </aside>
    </section>

@endsection